CustomerReview/Controllers/SocialMediaFormController.cs
using CustomerReview.Infrastructure;
using CustomerReview.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CustomerReview.Controllers
{
    public class SocialMediaFormController : Controller
    {
        public PartialViewResult StarSocialreviewlink(int officeId)
        {
            WebHttpRequest web = new WebHttpRequest();
            officeId = Convert.ToInt32(System.Web.HttpContext.Current.Session["officeId"].ToString());
            var content = web.Request("review/social-media/" + officeId + "/all", null, "GET");
            OfficeSocialMediaTypeModel model = new OfficeSocialMediaTypeModel();

            var splashinfo = JsonConvert.DeserializeObject<ResponseListModel<OfficeSocialMediaTypeModel>>(content);
            return PartialView("~/Views/SocialMediaForm/Partial/_StarSociallinkReview.cshtml", splashinfo.Data);
        }


        public PartialViewResult Customerfeedback(string rating)
        {
            CustomerReviewModel model = new CustomerReviewModel();
            model.Rating = Convert.ToDecimal(rating);
            return PartialView("~/Views/SocialMediaForm/Partial/_StarLinkReview.cshtml", model);
        }

        public ActionResult PostCustomerfeedback(CustomerReviewModel model)
        {
            WebHttpRequest web = new WebHttpRequest();
            CustomerReviewModel customerreview = new CustomerReviewModel();
            customerreview.OfficeId = Convert.ToInt32(System.Web.HttpContext.Current.Session["officeId"].ToString());
            customerreview.FirstName = model.FirstName;
            customerreview.LastName = model.LastName;
            customerreview.MessagesText = model.MessagesText;
            customerreview.Email = model.Email;
            customerreview.ContactNo = model.ContactNo;
            customerreview.Description = model.Description;
            customerreview.Rating = model.Rating;

            JavaScriptSerializer js = new JavaScriptSerializer();
            string jsonData = js.Serialize(customerreview);
            var content = web.Request("customer-review", jsonData, "POST");
            return RedirectToAction("Index", "CustomerReview", new { id = ProjectSession.ShortName });
        }

        [Route("~/error-404")]
        public ActionResult Error404()
        {
            return View();
        }
    }
}

CustomerReview/Views/SocialMediaForm/Partial/_StarLinkReview.cshtml
@model CustomerReview.Models.CustomerReviewModel


<style>
    .message {
        margin: 15px 30px 15px 15px;
        text-align: left;
        font-size: 20px !important;
        font-family: Roboto,"Open Sans","Helvetica Neue",Arial,Helvetica,sans-serif;
        font-weight: normal;
        font-style: normal;
        line-height: 100%;
        text-transform: none;
        line-height: 25px;
    }

    .validation {
        color: #FF0000 !important;
    }
</style>

<div class="modal-header">
    <h3 class="modal-title message" id="exampleModalLabel">
        We strive for 100% customer satisfaction. If we fell short, please tell us more so we can address your concerns.
    </h3>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        x
    </button>
</div>

@using (Html.BeginForm("PostCustomerfeedback", "SocialMediaForm", FormMethod.Post, new { @class = "m-form m-form--fit m-form--label-align-right", role = "form" }))
{
    @Html.HiddenFor(m => m.Rating)
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12 table-responsive">
                <div class="m-widget24">
                    <div class="m-widget24__item">
                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", placeholder = "Your FirstName*" })
                        @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "validation" })
                    </div>
                </div>
                <br />
                <div class="m-widget24">
                    <div class="m-widget24__item">
                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", placeholder = "Your LastName*" })
                        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "validation" })
                    </div>
                </div>
                <br />
                <div class="m-widget24">
                    <div class="m-widget24__item">
                        @Html.TextBoxFor(m => m.ContactNo, new { @class = "form-control", placeholder = "ContactNo" })
                        @Html.ValidationMessageFor(m => m.ContactNo, "", new { @class = "validation" })
                    </div>
                </div>
                <br />
                <div class="m-widget24">
                    <div class="m-widget24__item">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email*" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "validation" })
                    </div>
                </div>
                <br />
                <div class="m-widget24">
                    <div class="m-widget24__item">
                        @Html.LabelFor(m => m.MessagesText, new { @class = "m-list-settings__item-label", placeholder = "Message", @style = "font-weight:bold;" })
                        @Html.TextAreaFor(m => m.MessagesText, new { @class = "form-control", placeholder = "Message", @style = "width: 90%;" })
                        @Html.ValidationMessageFor(m => m.MessagesText, "", new { @class = "validation" })
                    </div>
                </div>
               <br />
                @if (CustomerReview.Infrastructure.ProjectSession.IsAllowCaptcha == true)
                {
                    <div class="m-widget24" style="margin-left: 230px;">
                        <div class="m-widget24__item">
                            <div class="g-recaptcha" data-sitekey="6LcgRWIUAAAAAG44vdVNXmJ578OvDMbfZ1LJ6k1E"></div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div class="col-md-offset-2 col-md-12">
            <button type="submit" class="btn btn-primary" value="Submit" id="btnconfirm">SEND MESSAGE</button>
        </div>
    </div>
}
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>
<script>
    $(document).ready(function () {
        console.log("ready!");
    });
    $('#btnconfirm').click(function () {
        if (grecaptcha.getResponse().length == 0) {
            alert('Please click the reCAPTCHA checkbox');
            return false;
        }
    });
</script>

CustomerReview/Views/SocialMediaForm/Partial/_StarSociallinkReview.cshtml
@model List<CustomerReview.Models.OfficeSocialMediaTypeModel>



<style>
    .message {
        margin: 15px 30px 15px 15px;
        text-align: left;
        font-size: 20px !important;
        font-family: Roboto,"Open Sans","Helvetica Neue",Arial,Helvetica,sans-serif;
        font-weight: normal;
        font-style: normal;
        line-height: 100%;
        text-transform: none;
        line-height: 25px;
    }

    
.logo-section .m-widget24 {
    float: left;
    margin: 10px;
}

.logo-section h5 {
    width: 100%;
    clear: both;
}
</style>



<div class="modal-header">
    <h3 class="modal-title message" id="exampleModalLabel">
        Thank you! <b>We need your help.</b> Would you share your experience on one of these sites?
    </h3>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
       x
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-md-12 table-responsive logo-section">
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <div class="m-widget24">
                        <div class="m-widget24__item">
                         <a href="@item.RedirectionURL">   
                            <img src="@item.SocialMediaIconURL" class="btn m-btn--square  btn-secondary" style="margin: 0 1px 5px 0;" />
                          </a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
        Close
    </button>
</div>